---
"workspace:move_tab_right": none
"pane_group:navigate_right": none
"workspace:activate_last_tab": alt-9
"workspace:activate_sixth_tab": alt-6
"pane_group:add_up": none
"terminal:select_bookmark_up": none
"workspace:activate_eighth_tab": alt-8
"workspace:activate_third_tab": alt-3
"workspace:activate_first_tab": alt-1
"pane_group:add_left": ctrl-shift-E
"workspace:activate_second_tab": alt-2
"pane_group:add_down": ctrl-shift-D
"editor_view:add_cursor_below": none
"workspace:activate_prev_tab": alt-down
"workspace:activate_fifth_tab": alt-5
"editor_view:move_backward_one_subword": none
"workspace:activate_next_tab": alt-up
"terminal:select_bookmark_down": none
"pane_group:navigate_left": none
"pane_group:add_right": none
"workspace:move_tab_left": none
"editor_view:add_cursor_above": none
"workspace:activate_seventh_tab": alt-7
"workspace:rename_active_tab": f2
"editor_view:move_forward_one_subword": none
"workspace:activate_fourth_tab": alt-4
"input:clear_screen": ctrl-escape
